version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo "¡Compilacion exitosa, ahora ejecuta las pruebas unitarias!"
      - python -m pytest tests/
artifacts:
  files:
    - '**/*'
