version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
      - pip install pytest

  build:
    commands:
      - echo "¡Compilacion exitosa, ahora ejecuta las pruebas unitarias!"
      - python -m pytest tests/

artifacts:
  files:
    - '**/*'
